export const BILL_DETAIL_SUCCESS = 'BILL_DETAIL_SUCCESS'
export const BILL_DETAIL_FAILURE = 'BILL_DETAIL_FAILURE'

export const BILL_LIST_SUCCESS = 'BILL_LIST_SUCCESS'
export const BILL_LIST_FAILURE = 'BILL_LIST_FAILURE'